name: disposed
description: |
  Automatically disposable wrappers for objects utilizing Finalizer.
  Auto closable StreamController is included!
version: 1.0.0
homepage: https://github.com/Zekfad/disposed
repository: https://github.com/Zekfad/disposed
issue_tracker: https://github.com/Zekfad/disposed/issues
# documentation: https://pub.dev/documentation/disposed/latest/

topics:
  - gc
  - disposable
  - streams

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3
  zekfad_lints: ^1.2.0
